= enneagram-explorer
:source-highlighter: highlightjs

The Enneagram Explorer is a WebApp to quickly look up some of the most important aspects of the Enneagram. You can use it when you've just got your mobile at hand but not all your great books.

Currently, it's only in German available. Translations and help with including some i18n tool are warmly appreciated. :-)

You can see a live demo at https://ptandler.github.io/enneagram-explorer/

== Project setup

I use yarn instead of npm in this project.

```
yarn install
```

== Compiles and hot-reloads for development
```
yarn run serve
```

== Compiles and minifies for production
```
yarn run build
```

== Run your tests
```
yarn run test
```

== Lints and fixes files
```
yarn run lint
```

== ToDo Ideas

* add i18n

== Changelog

=== v0.3.0

* added pinch zoom for font-size

=== v0.2.2 (2019-08-21)

First more or less nicely working version.

== Update Enneagram.svg

How to update the embedded Enneagram.svg:

[source,bash]
----
$ git fetch enneagram.svg master
$ git subtree pull --prefix src/assets/enneagram enneagram.svg master
----

You might want to consider the `--squash` option when pulling / merging.

== Favicon

The favicons are generated by https://realfavicongenerator.net[RealFaviconGenerator]:

1. `yarn favicon:generate`
2. `yarn favicon:inject`

See also https://realfavicongenerator.net/api/non_interactive_api and https://realfavicongenerator.net/api/interactive_api.

== Related Work

* https://github.com/juliajessica/enneagram
* https://github.com/loverthehater/id-ennea
* https://github.com/nthmost/rheti-python[the official enneagram test (RHETI) written in python for command line and api use.]
